name = "MultitypeBranchingProcessInference"
uuid = "308293ef-aee2-4ae5-b65c-832e3cc62f62"
authors = ["angus-lewis <angus.lewis@adelaide.edu.au> and contributors"]
version = "1.0.0-DEV"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
KalmanFilters = "87bd2298-8e87-4e6e-a3ab-44099389f11c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetropolisHastings = "55b51500-bf1d-489d-9500-8ff68ba15a90"
MultitypeBranchingProcesses = "03374bc4-a2c9-49a3-a3a8-2ad9c27ec437"
ParticleFilter = "d24d8225-d2ad-4b74-bd26-b62f0c3ae121"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Distributions = "0.25.115"
LinearAlgebra = "1.11.0"
Random = "1.11.0"
Reexport = "1.2.2"
StableRNGs = "1.0.2"
StaticArrays = "1.9.13"
julia = "1.6.7"

[extras]
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StableRNGs"]
