env: 
  blas_num_threads: 1

model:
  stateprocess:
    params:
      E_state_count: 1
      I_state_count: 1
      is_time_homogeneous: false
      timestamps: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0, 42.0, 49.0, 56.0, 63.0, 70.0, 77.0, 84.0, 91.0]
      R_0: [1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1]
      T_E: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
      T_I: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      observation_probability: 0.75
      immigration_rate: nothing # [0.0, 0.0, 0.0, 0.0]
    # [E, I, O]
    initial_state: [10, 0, 0]
  observation:
    mean: [0.0]
    cov: [400.0]

inference:
  data: 
    filename: data/observations.csv
    first_observation_time: 1.0
  likelihood_approx:
    method: kalman_filter
    switch:
      threshold: 20
      seed: 1516171819
    particle_filter:
      seed: 67890
      nparticles: 256
      multithreadded: false
  prior_parameters:
    R_0:
      type: gaussian_processes
      covariance_function: exponential
      mu: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      ell: 136.47008022356596
      sigma: 0.7
      transform: log
    initial_state:
      mu: [10.0, 10.0]
      cov: [10.0, 0.0, 0.0, 10.0]
  proposal_parameters:
    mean: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    cov: [1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e-5]
  mh_config:
    seed: 1011121314
    thin: 1
    buffer_size: 16384
    outfilename: data/expcovfn_vic_covid_kalman_param_samples.f64_array.bin
    max_iters: 831072
    nparams: 16 # 14
    max_time_sec: 604800.0 # 1 week!
    # [R_0_1, R_0_2, ..., R_0_14]
    init_sample: [2.214743332299293, 2.6967066321185844, 2.167452882032263, 2.359025973872552, 2.1045936334458486, 1.9690462905306627, 1.4794144545843726, 1.3941797483724367, 1.2432786509359939, 0.7641490313968745, 0.6729689849702709, 0.5254615752270348, 0.5538658257704514, 0.6020087633774175, 4.0, 4.0]
    verbose: true
    infofilename: data/expcovfn_vic_covid_kalman.info.txt
    model_info_filename: data/model_info_expcovfn_vic_covid_kalman.info.txt
    model_info_thin: 32
    adaptive: true
    nadapt: 131072
    adapt_cov_scale: 1.0
    continue: false