env: 
  blas_num_threads: 1

simulation:
  seed: 12345
  outfilename: data/seir_sim_particles_0.5_obs_prob.Int64.bin
  tstep: 1
  nsteps: 100

model:
  stateprocess:
    params:
      E_state_count: 8
      I_state_count: 8
      is_time_homogeneous: true
      exposed_stage_change_rate: 0.6
      infection_rate: 0.06
      infectious_stage_change_rate: 0.17142857142857143
      observation_probability: 0.75
      immigration_rate: nothing
    # [E, I, O, R]
    initial_state: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1, 0]
  observation:
    mean: [0.0]
    cov: [1.0]

inference:
  likelihood_approx:
    method: particle_filter
    switch:
      threshold: 1.25
      seed: 1516171819
    particle_filter:
      seed: 67890
      nparticles: 256
  prior_parameters:
    R_0:
      shape: 4.4
      scale: 0.5
  proposal_parameters:
    mean: [0.0]
    cov: [1.0]
  mh_config:
    seed: 1011121314
    buffer_size: 4096
    outfilename: data/test_samples.f64_array.bin
    max_iters: 81920
    nparams: 1
    # max_time_sec: 1500.0
    max_time_sec: 604800.0
    # [R_0]
    init_sample: [2.8]
    verbose: true
    infofilename: data/test_samples.info.txt
    adaptive: true
    nadapt: 20480
    adapt_cov_scale: 8.0
    continue: false
    thin: 1
    model_info_thin: 1

state_inference:
  pfseed: 2021222324
  switchseed: 2526272829
  threshold: 1.25
  nparticles: 4096
  tsteps: [8, 16, 31, 61, 91]
  states: [4, 12]

benchmarks:
  pfseed: 2021222324
  switchseed: 2526272829
  bootseed: 3131323334
  thresholds: [6, 10]
  nparticles: [512, 1024, 2048]
  nsamples: 2048
